import { Company, Contact, Deal, Lead, Task, Activity, Member } from '../types/crm';

export function generateSampleCRMData(orgId: string, members: Member[]) {
  const adminMember = members.find((m) => m.role === 'Owner/Admin') || members[0];
  const rep1 = members.find((m) => m.role === 'Sales Rep') || adminMember;
  const rep2 = members.find((m) => m.role === 'Manager') || adminMember;

  const now = new Date();
  const pastDays = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();
  const futureDays = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString();
  const todayAt = (hours: number) => {
    const d = new Date(now);
    d.setHours(hours, 0, 0, 0);
    return d.toISOString();
  };

  const sampleCompanies: Company[] = [
    {
      id: 'comp_1',
      organizationId: orgId,
      name: 'Apex Logistics Inc.',
      industry: 'Freight & Supply Chain',
      website: 'https://apexlogistics.example.com',
      size: '50-100 employees',
      ownerId: rep1.uid,
      ownerName: rep1.name,
      phone: '+1 (555) 234-5678',
      email: 'ops@apexlogistics.example.com',
      address: '1420 Harbor Blvd, Long Beach, CA',
      notes: 'Expanding fleet by 30 trucks this quarter. Looking for dispatch automation.',
      createdAt: pastDays(35),
      updatedAt: pastDays(2),
    },
    {
      id: 'comp_2',
      organizationId: orgId,
      name: 'Beacon Health Systems',
      industry: 'Healthcare Software',
      website: 'https://beaconhealth.example.com',
      size: '150-250 employees',
      ownerId: rep2.uid,
      ownerName: rep2.name,
      phone: '+1 (555) 876-5432',
      email: 'info@beaconhealth.example.com',
      address: '77 Medical Center Way, Boston, MA',
      notes: 'HIPAA compliance audit completed. Ready for contract negotiation.',
      createdAt: pastDays(45),
      updatedAt: pastDays(10), // Note: >7 days, candidate for stale
    },
    {
      id: 'comp_3',
      organizationId: orgId,
      name: 'Cascade Retail Solutions',
      industry: 'E-commerce & Point of Sale',
      website: 'https://cascaderetail.example.com',
      size: '20-50 employees',
      ownerId: rep1.uid,
      ownerName: rep1.name,
      phone: '+1 (555) 345-6789',
      email: 'sales@cascaderetail.example.com',
      address: '908 Pine Street, Seattle, WA',
      notes: 'Migrating legacy POS systems to cloud platforms.',
      createdAt: pastDays(20),
      updatedAt: pastDays(1),
    },
    {
      id: 'comp_4',
      organizationId: orgId,
      name: 'Zenith BioAnalytics',
      industry: 'Biotechnology',
      website: 'https://zenithbio.example.com',
      size: '10-30 employees',
      ownerId: adminMember.uid,
      ownerName: adminMember.name,
      phone: '+1 (555) 901-2345',
      email: 'contact@zenithbio.example.com',
      address: '400 Science Park, Cambridge, MA',
      notes: 'Series A funded venture looking for enterprise tracking tools.',
      createdAt: pastDays(15),
      updatedAt: pastDays(12),
    },
  ];

  const sampleContacts: Contact[] = [
    {
      id: 'cont_1',
      organizationId: orgId,
      name: 'Elena Rostova',
      email: 'elena.rostova@apexlogistics.example.com',
      phone: '+1 (555) 234-5679',
      companyId: 'comp_1',
      companyName: 'Apex Logistics Inc.',
      title: 'VP of Operations',
      ownerId: rep1.uid,
      ownerName: rep1.name,
      source: 'Cold Outreach',
      tags: ['Decision Maker', 'High Intent'],
      notes: 'Prefers afternoon check-in calls. Highly focused on ROI within 6 months.',
      lastContactedAt: pastDays(2),
      nextFollowUpAt: todayAt(14),
      createdAt: pastDays(30),
      updatedAt: pastDays(2),
    },
    {
      id: 'cont_2',
      organizationId: orgId,
      name: 'Dr. Marcus Vance',
      email: 'm.vance@beaconhealth.example.com',
      phone: '+1 (555) 876-5433',
      companyId: 'comp_2',
      companyName: 'Beacon Health Systems',
      title: 'Chief Technology Officer',
      ownerId: rep2.uid,
      ownerName: rep2.name,
      source: 'Inbound Demo',
      tags: ['Technical Lead'],
      notes: 'Requested security whitepaper on cloud data encryption.',
      lastContactedAt: pastDays(10),
      nextFollowUpAt: pastDays(3), // OVERDUE follow-up!
      createdAt: pastDays(40),
      updatedAt: pastDays(10),
    },
    {
      id: 'cont_3',
      organizationId: orgId,
      name: 'Sarah Chen',
      email: 'sarah.c@cascaderetail.example.com',
      phone: '+1 (555) 345-6780',
      companyId: 'comp_3',
      companyName: 'Cascade Retail Solutions',
      title: 'Head of Growth',
      ownerId: rep1.uid,
      ownerName: rep1.name,
      source: 'Referral',
      tags: ['Fast Mover'],
      notes: 'Budget already approved for Q4 rollout.',
      lastContactedAt: pastDays(1),
      nextFollowUpAt: futureDays(2),
      createdAt: pastDays(18),
      updatedAt: pastDays(1),
    },
  ];

  const sampleDeals: Deal[] = [
    // Healthy deal with next action
    {
      id: 'deal_1',
      organizationId: orgId,
      title: 'Fleet Automation Suite (30 Trucks)',
      companyId: 'comp_1',
      companyName: 'Apex Logistics Inc.',
      contactId: 'cont_1',
      contactName: 'Elena Rostova',
      ownerId: rep1.uid,
      ownerName: rep1.name,
      pipelineId: 'default',
      stageId: 'proposal',
      value: 38000,
      probability: 60,
      expectedCloseDate: futureDays(21),
      status: 'Open',
      priority: 'High',
      lastActivityAt: pastDays(2),
      nextAction: 'Send revised SLA and quote for custom integrations',
      nextActionAt: todayAt(15), // Due today!
      notes: 'Client reviewed demo positively, requested tailored SLA terms.',
      createdAt: pastDays(25),
      updatedAt: pastDays(2),
    },
    // Stale deal (>7 days inactive) & Overdue follow-up
    {
      id: 'deal_2',
      organizationId: orgId,
      title: 'Enterprise Clinical Cloud Migration',
      companyId: 'comp_2',
      companyName: 'Beacon Health Systems',
      contactId: 'cont_2',
      contactName: 'Dr. Marcus Vance',
      ownerId: rep2.uid,
      ownerName: rep2.name,
      pipelineId: 'default',
      stageId: 'negotiation',
      value: 75000, // High-value deal at risk!
      probability: 70,
      expectedCloseDate: futureDays(14),
      status: 'Open',
      priority: 'High',
      lastActivityAt: pastDays(11), // Inactive > 7 days = STALE!
      nextAction: 'Final executive security sign-off meeting',
      nextActionAt: pastDays(3), // OVERDUE!
      notes: 'CTO expressed enthusiasm but procurement stalled review.',
      createdAt: pastDays(40),
      updatedAt: pastDays(11),
    },
    // Deal without next step (action center trigger)
    {
      id: 'deal_3',
      organizationId: orgId,
      title: 'Cloud POS Integration Pilot',
      companyId: 'comp_3',
      companyName: 'Cascade Retail Solutions',
      contactId: 'cont_3',
      contactName: 'Sarah Chen',
      ownerId: rep1.uid,
      ownerName: rep1.name,
      pipelineId: 'default',
      stageId: 'qualified',
      value: 16500,
      probability: 30,
      expectedCloseDate: futureDays(30),
      status: 'Open',
      priority: 'Medium',
      lastActivityAt: pastDays(3),
      nextAction: '', // MISSING NEXT STEP!
      nextActionAt: '',
      notes: 'Initial requirements gathered. Needs follow-up scheduling.',
      createdAt: pastDays(12),
      updatedAt: pastDays(3),
    },
    // Closed Won deal
    {
      id: 'deal_4',
      organizationId: orgId,
      title: 'Initial Analytics Sandbox Trial',
      companyId: 'comp_4',
      companyName: 'Zenith BioAnalytics',
      ownerId: adminMember.uid,
      ownerName: adminMember.name,
      pipelineId: 'default',
      stageId: 'closed-won',
      value: 24000,
      probability: 100,
      expectedCloseDate: pastDays(4),
      status: 'Won',
      priority: 'Medium',
      lastActivityAt: pastDays(4),
      nextAction: 'Customer success onboarding kickoff',
      nextActionAt: pastDays(1),
      notes: 'Contract signed and first invoice issued.',
      createdAt: pastDays(30),
      updatedAt: pastDays(4),
    },
    // Closed Lost deal
    {
      id: 'deal_5',
      organizationId: orgId,
      title: 'Warehouse Telemetry Upgrade',
      companyId: 'comp_1',
      companyName: 'Apex Logistics Inc.',
      ownerId: rep1.uid,
      ownerName: rep1.name,
      pipelineId: 'default',
      stageId: 'closed-lost',
      value: 12000,
      probability: 0,
      expectedCloseDate: pastDays(15),
      status: 'Lost',
      priority: 'Low',
      lastActivityAt: pastDays(15),
      nextAction: 'Re-engage next fiscal year',
      notes: 'Deferred to next budget cycle due to warehouse expansion delays.',
      createdAt: pastDays(45),
      updatedAt: pastDays(15),
    },
    // New qualified deal
    {
      id: 'deal_6',
      organizationId: orgId,
      title: 'Multi-Location Inventory Sync',
      companyId: 'comp_3',
      companyName: 'Cascade Retail Solutions',
      contactId: 'cont_3',
      contactName: 'Sarah Chen',
      ownerId: rep1.uid,
      ownerName: rep1.name,
      pipelineId: 'default',
      stageId: 'new',
      value: 22000,
      probability: 10,
      expectedCloseDate: futureDays(45),
      status: 'Open',
      priority: 'Medium',
      lastActivityAt: pastDays(1),
      nextAction: 'Schedule technical discovery call with solutions architect',
      nextActionAt: futureDays(1),
      notes: 'Requested integration capabilities with Shopify Plus.',
      createdAt: pastDays(2),
      updatedAt: pastDays(1),
    },
  ];

  const sampleLeads: Lead[] = [
    {
      id: 'lead_1',
      organizationId: orgId,
      name: 'David Reynolds',
      companyName: 'Vanguard Freightways',
      email: 'd.reynolds@vanguardfreight.example.com',
      phone: '+1 (555) 456-7890',
      source: 'Website Form',
      status: 'New', // Awaiting action!
      priority: 'High',
      ownerId: rep1.uid,
      ownerName: rep1.name,
      estimatedValue: 45000,
      notes: 'Submitted demo request form 2 hours ago. Looking for rapid quote.',
      createdAt: pastDays(0.1),
      updatedAt: pastDays(0.1),
    },
    {
      id: 'lead_2',
      organizationId: orgId,
      name: 'Maya Patel',
      companyName: 'BioHealth Diagnostics',
      email: 'maya@biohealthdiag.example.com',
      phone: '+1 (555) 789-0123',
      source: 'Inbound Web',
      status: 'Contacted',
      priority: 'Medium',
      ownerId: rep2.uid,
      ownerName: rep2.name,
      estimatedValue: 28000,
      lastContactedAt: pastDays(2),
      nextFollowUpAt: pastDays(1), // Overdue lead follow-up!
      notes: 'Introductory email sent, awaiting response on scheduling demo.',
      createdAt: pastDays(5),
      updatedAt: pastDays(2),
    },
    {
      id: 'lead_3',
      organizationId: orgId,
      name: 'Julian Mercer',
      companyName: 'Skyline E-Commerce',
      email: 'julian@skyline-ecom.example.com',
      phone: '+1 (555) 678-9012',
      source: 'LinkedIn',
      status: 'Qualified',
      priority: 'High',
      ownerId: rep1.uid,
      ownerName: rep1.name,
      estimatedValue: 19000,
      lastContactedAt: pastDays(1),
      nextFollowUpAt: todayAt(11), // Due today!
      notes: 'Discussed API connectors. Ready to convert to Opportunity.',
      createdAt: pastDays(7),
      updatedAt: pastDays(1),
    },
    {
      id: 'lead_4',
      organizationId: orgId,
      name: 'Claire Beauchamp',
      companyName: 'Harbor Shipping Group',
      email: '', // Data quality issue example!
      phone: '',
      source: 'Event Booth',
      status: 'New',
      priority: 'Low',
      ownerId: '',
      estimatedValue: 10000,
      notes: 'Met at Logistics Expo. Need to locate business card for contact info.',
      createdAt: pastDays(3),
      updatedAt: pastDays(3),
    },
  ];

  const sampleTasks: Task[] = [
    {
      id: 'task_1',
      organizationId: orgId,
      title: 'Call Dr. Vance regarding HIPAA security addendum',
      type: 'Call',
      description: 'Review updated data encryption clauses with Beacon Health procurement team.',
      ownerId: rep2.uid,
      ownerName: rep2.name,
      dueAt: pastDays(2), // Overdue task!
      priority: 'High',
      status: 'Pending',
      relatedEntityType: 'deal',
      relatedEntityId: 'deal_2',
      relatedEntityName: 'Enterprise Clinical Cloud Migration',
      createdAt: pastDays(5),
    },
    {
      id: 'task_2',
      organizationId: orgId,
      title: 'Prepare revised SLA proposal for Apex Logistics',
      type: 'To-Do',
      description: 'Detail 99.95% uptime guarantees and dedicated account manager inclusion.',
      ownerId: rep1.uid,
      ownerName: rep1.name,
      dueAt: todayAt(16), // Due today!
      priority: 'High',
      status: 'In Progress',
      relatedEntityType: 'deal',
      relatedEntityId: 'deal_1',
      relatedEntityName: 'Fleet Automation Suite (30 Trucks)',
      createdAt: pastDays(2),
    },
    {
      id: 'task_3',
      organizationId: orgId,
      title: 'Conduct discovery demo with David Reynolds',
      type: 'Meeting',
      description: 'Demonstrate fleet tracking dashboard and custom webhook capabilities.',
      ownerId: rep1.uid,
      ownerName: rep1.name,
      dueAt: futureDays(1),
      priority: 'Medium',
      status: 'Pending',
      relatedEntityType: 'lead',
      relatedEntityId: 'lead_1',
      relatedEntityName: 'David Reynolds (Vanguard Freightways)',
      createdAt: pastDays(0.1),
    },
    {
      id: 'task_4',
      organizationId: orgId,
      title: 'Finalize onboarding checklist for Zenith BioAnalytics',
      type: 'Follow-up',
      description: 'Verify all admin user invites have been issued and training scheduled.',
      ownerId: adminMember.uid,
      ownerName: adminMember.name,
      dueAt: pastDays(1),
      priority: 'Medium',
      status: 'Completed',
      relatedEntityType: 'deal',
      relatedEntityId: 'deal_4',
      relatedEntityName: 'Initial Analytics Sandbox Trial',
      createdAt: pastDays(4),
      completedAt: pastDays(1),
    },
  ];

  const sampleActivities: Activity[] = [
    {
      id: 'act_1',
      organizationId: orgId,
      type: 'Call',
      subject: 'Discovery Call with Elena Rostova',
      description: 'Discussed fleet expansion plans and current dispatch bottlenecks.',
      actorId: rep1.uid,
      actorName: rep1.name,
      relatedEntityType: 'deal',
      relatedEntityId: 'deal_1',
      relatedEntityName: 'Fleet Automation Suite (30 Trucks)',
      occurredAt: pastDays(2),
      createdAt: pastDays(2),
    },
    {
      id: 'act_2',
      organizationId: orgId,
      type: 'Email',
      subject: 'Security Documentation Forwarded to Dr. Vance',
      description: 'Sent SOC 2 Type II summary report and BAA template.',
      actorId: rep2.uid,
      actorName: rep2.name,
      relatedEntityType: 'deal',
      relatedEntityId: 'deal_2',
      relatedEntityName: 'Enterprise Clinical Cloud Migration',
      occurredAt: pastDays(11),
      createdAt: pastDays(11),
    },
    {
      id: 'act_3',
      organizationId: orgId,
      type: 'Meeting',
      subject: 'Executive Contract Signing & Champagne Toast',
      description: 'Executed annual subscription agreement with Zenith BioAnalytics.',
      actorId: adminMember.uid,
      actorName: adminMember.name,
      relatedEntityType: 'deal',
      relatedEntityId: 'deal_4',
      relatedEntityName: 'Initial Analytics Sandbox Trial',
      occurredAt: pastDays(4),
      createdAt: pastDays(4),
    },
    {
      id: 'act_4',
      organizationId: orgId,
      type: 'Note',
      subject: 'Competitive Intel Note',
      description: 'Cascade Retail is also evaluating an offshore alternative, but prefers our local support.',
      actorId: rep1.uid,
      actorName: rep1.name,
      relatedEntityType: 'company',
      relatedEntityId: 'comp_3',
      relatedEntityName: 'Cascade Retail Solutions',
      occurredAt: pastDays(1),
      createdAt: pastDays(1),
    },
  ];

  return {
    companies: sampleCompanies,
    contacts: sampleContacts,
    deals: sampleDeals,
    leads: sampleLeads,
    tasks: sampleTasks,
    activities: sampleActivities,
  };
}
